### ISSUE TITLE
Type in Scroll to Column Dropdown

### ISSUE THREAD

**Issue by silverbullettruck2001** [aminosoftware/lysine#21]
Allow user to be able to type in the Column Name in the 'Scroll To Column' dropdown on the Cell Value Viewer.  If precise match isn't found return columns that partially match what was entered.

**Comment by benharrell** [comment]
was able to get a slightly different version of this, now the dropdown is alpha sorted to make finding a column easier and auto-complete will  suggest...

ver 2805
