### ISSUE TITLE
Layout Doesn't Save Multiple FlagColumns for RedefineSet

### ISSUE THREAD

**Issue by silverbullettruck2001** [aminosoftware/lysine#24]
I have a Redefine column that is made up of 2 FlagClolumns columns.  For example, ColA and ColB which are outside of the Redefine.  I click the dropdown on the FlagColumn field and check the boxes next to each of the columns, ColA and ColB.  I have each of the RedefineSet columns setup with FlagColumnValue expressions so that both ColA and ColB values are checked.  If I go to the 'Layout' tab and preview my changes it works perfectly.  However, if I click 'Ok' to save my changes to the connection manager, then re-open the connection manager, the FlagColumn only saved the checked value for ColA, but not ColB so if I go to the Layout tab and click Generate, it fails.  If I go back and check the box next to ColB on the FlagColumn for the Redefine, it works again, but it won't ever save that value so the package fails.

**Comment by benharrell** [comment]
fixed in build 2805...was a persistence issue for multi values in a redefine set.   

also changed the display for comparison values to more readable format:

[column id]   equals 123 (AND) [column id2] equals 456

**Comment by silverbullettruck2001** [comment]
This worked like a charm!  Thanks for the fix!
