### ISSUE TITLE
Editing list within Comparison Builder

### ISSUE THREAD

**Issue by silverbullettruck2001** [aminosoftware/lysine#26]
If you go in and setup a list of possible values for a FlagColumnValue and then click OK.  Then try to go back and want to make changes to that list of values, the list is blank instead of being populated with the previously entered list values.  If you have entries for the 'Equals' comparison, they show up fine when going out and back into the Comparison Builder.  It just seems to be an issue for the 'List' box where it won't show the actual list of values.  This is a pain because any changes to the list requires you to reenter the entire list instead of just making the one change.

**Comment by benharrell** [comment]
fixed in build 2805

**Comment by silverbullettruck2001** [comment]
@benharrell, Sweet!  Can't wait for the next patch!
