### ISSUE TITLE
Import Layout XML encoding

### ISSUE THREAD

**Issue by silverbullettruck2001** [aminosoftware/lysine#30]
When exporting a layout file the XML declaration is <?xml version="1.0" ?>, if you modify it to fit normal xml standards to be <?xml version="1.0" encoding="utf-8"?> the parser will throw an error of "Name cannot being with the '.' character, hexadecimal value 0x00".  If you remove the 'encoding="utf-8"' it works fine, but the XML is valid, unless there is some other encoding being used by Lysine.  Could you make the file import process handle the encoding attribute in the XML declaration?

**Comment by benharrell** [comment]
fixed in build 2805...was defaulting to unicode...switched to UTF8 default for xml loading
