### ISSUE TITLE
Version info on the License tab

### ISSUE THREAD

**Issue by silverbullettruck2001** [aminosoftware/lysine#4]
Please add build version information to the License tab in Lysine so you can see what version of the tool you are running.

**Comment by benharrell** [comment]
Next release will contain version info on license tab AND as an info event in the runtime log


<img width="477" alt="screen shot 2017-08-07 at 8 13 09 pm" src="https://user-images.githubusercontent.com/29810/29050920-f1336866-7bac-11e7-89f6-f74a16dc48b3.png">
<img width="457" alt="screen shot 2017-08-07 at 8 12 49 pm" src="https://user-images.githubusercontent.com/29810/29050925-fa4b88ac-7bac-11e7-8fcd-a319a93866df.png">
