### ISSUE TITLE
How can we use Expression in Lysine connection manager

### ISSUE THREAD

**Issue by abhikadamRP** [aminosoftware/lysine#49]
I am trying to use a dynamic source path, by using the expression. How can I achieve it?
![image](https://user-images.githubusercontent.com/99762177/160403412-64bd1ed5-6ff8-46b7-ac5c-d9331a311b94.png)

![image](https://user-images.githubusercontent.com/99762177/160403641-6bb3af72-de3a-457e-8b80-6238f7c40ce9.png)

**Comment by benharrell** [comment]
In SSIS all of the Connection Manager events were too early to get the updated variable value in some rare cases so we added a property to the Source Component which can evaluate the filename variable RIGHT before it executes and eliminate any "staleness".  If you assign your variable to the "Override Filename Value" property on the EBCDIC Source Component it should work.
